### ISSUE TITLE
error SpaceSkyRenderer on 2020.2,2020.3

### ISSUE THREAD

**Issue by InfiBatnis** [Dreaming381/lsss-wip#5]
Assets\_Code\Rendering\SpaceSkyRenderer.cs(42,46): error CS0619: 'HDRenderUtilities.CreateReflectionProbeRenderTarget(int)' is obsolete: 'Use CreateReflectionProbeRenderTarget with explicit format instead'

Not problem at unity 2020.1 - HDRP 9.0.0
Problem at 2020.2,2020.3- HDRP 10.4.0
2021.1(No Test),2021.2(No Test)

**Comment by Dreaming381** [comment]
Thanks for reporting!

Unlike the Latios Framework, I do not validate LSSS beyond its current version. So this issue will be fixed once LSSS is upgraded to a later Unity version. I expect this to happen shortly after the next DOTS release.

**Comment by InfiBatnis** [comment]
OK
