### ISSUE TITLE
did i do something wrong?

### ISSUE THREAD

**Issue by silverlint** [Dreaming381/lsss-wip#6]
ObjectDisposedException: Attempted to access Unity.Entities.EntityTypeHandle which has been invalidated by a structural change.
Unity.Entities.WorldUnmanagedImpl+UnmanagedUpdate_00001541$BurstDirectCall.Invoke (System.Void* pSystemState) (at <54c68c86110c4e6e8ed0c9593c5cc484>:0)
Unity.Entities.WorldUnmanagedImpl.UnmanagedUpdate (System.Void* pSystemState) (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/WorldUnmanaged.cs:810)
Unity.Entities.WorldUnmanagedImpl.UpdateSystem (Unity.Entities.SystemHandle sh) (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/WorldUnmanaged.cs:895)
Unity.Entities.SystemHandle.Update (Unity.Entities.WorldUnmanaged world) (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/WorldUnmanaged.cs:169)
Latios.SuperSystem.UpdateUnmanagedSystem (Latios.LatiosWorldUnmanagedImpl* impl, Unity.Entities.SystemHandle system) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:260)
Latios.SuperSystem.UpdateAllSystems (Unity.Entities.ComponentSystemGroup group, Unity.Entities.Exposed.SystemSortingTracker& tracker) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:325)
UnityEngine.Debug:LogException(Exception)
Latios.SuperSystem:UpdateAllSystems(ComponentSystemGroup, SystemSortingTracker&) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:335)
Latios.SuperSystem:DoSuperSystemUpdate(ComponentSystemGroup, SystemSortingTracker&) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:358)
Latios.Systems.LatiosWorldSyncGroup:OnUpdate() (at ./Packages/com.latios.latios-framework/Core/Systems/_Essentials/LatiosInitializationSystemGroup.cs:60)
Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/SystemBase.cs:418)
Latios.SuperSystem:UpdateManagedSystem(LatiosWorldUnmanagedImpl*, ComponentSystemBase) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:292)
Latios.SuperSystem:UpdateAllSystems(ComponentSystemGroup, SystemSortingTracker&) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:330)
Latios.SuperSystem:DoSuperSystemUpdate(ComponentSystemGroup, SystemSortingTracker&) (at ./Packages/com.latios.latios-framework/Core/Framework/SuperSystem.cs:358)
Latios.Systems.LatiosInitializationSystemGroup:OnUpdate() (at ./Packages/com.latios.latios-framework/Core/Systems/_Essentials/LatiosInitializationSystemGroup.cs:43)
Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/SystemBase.cs:418)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.0-pre.65/Unity.Entities/ScriptBehaviourUpdateOrder.cs:526)

I clicked on a mission in the title menu but it doesn't work properly

**Comment by Dreaming381** [comment]
Nope. That's a regression. Will fix shortly!

Side note, I usually only test entering play mode in a mission directly before pushing. I only test scene switching and builds when I get really close to a new framework release.

**Comment by Dreaming381** [comment]
Should be fixed now!
